// Daftar kecamatan di Kabupaten Banyuwangi
export const KECAMATAN_BANYUWANGI: string[] = [
  'Bangorejo',
  'Banyuwangi',
  'Blimbingsari',
  'Cluring',
  'Gambiran',
  'Genteng',
  'Giri',
  'Glagah',
  'Glenmore',
  'Kabat',
  'Kalibaru',
  'Kalipuro',
  'Licin',
  'Muncar',
  'Pesanggaran',
  'Purwoharjo',
  'Rogojampi',
  'Sempu',
  'Siliragung',
  'Singojuruh',
  'Songgon',
  'Srono',
  'Tegaldlimo',
  'Tegalsari',
  'Wongsorejo',
]
